// export loadInfo from './loadInfo';
// export login from './login';
// export logout from './logout';
// export * as widget from './widget/index';
// export * as survey from './survey/index';
export loadAuth from './loadAuth';
export loadTags from './loadTags';
export getMetaData from './getMetaData';
export postSuggestion from './postSuggestion';
export getPreview from './getPreview';
export getResourcesCount from './getResourcesCount';
export saveResource from './saveResource';
export createAccessToken from './createAccessToken';
